Repository netlify/open-api, pull requests merged in 2020-09, with the labels that each got.

#253 Update README.md
  README.md
Labels: type: chore

#258 Fix service instance swagger definition
  swagger.yml
Labels: type: bug

#259 chore: regenerate go client
  go/models/user.go
  go/plumbing/operations/create_split_test_swagger_responses.go
  go/plumbing/operations/delete_service_instance_parameters.go
  go/plumbing/operations/delete_service_instance_responses.go
  go/plumbing/operations/disable_split_test_swagger_responses.go
  go/plumbing/operations/enable_split_test_swagger_responses.go
  go/plumbing/operations/get_split_test_swagger_responses.go
  go/plumbing/operations/get_split_tests_responses.go
  go/plumbing/operations/operations_client.go
  go/plumbing/operations/show_service_instance_parameters.go
  go/plumbing/operations/show_service_instance_responses.go
  go/plumbing/operations/unlink_site_repo_parameters.go
  go/plumbing/operations/unlink_site_repo_responses.go
  go/plumbing/operations/update_service_instance_parameters.go
  go/plumbing/operations/update_service_instance_responses.go
  go/plumbing/operations/update_split_test_swagger_responses.go
Labels: type: chore

#262 Add WaitUntilDeployLive Go client method
  go/porcelain/deploy.go
Labels: type: feature
