Repository netlify/open-api, pull requests merged in 2020-07, with the labels that each got.

#242 Document `/sites/{site_id}/unlink_repo`
  swagger.yml
Labels: api-documentation, type: feature

#243 Remove support_priority field
  swagger.yml
Labels: type: chore

#247 fix sites typo on split test endpoint paths
  swagger.yml
Labels: type: bug
