Repository netlify/open-api, pull requests merged in 2021-01, with the labels that each got.

#278 feat: add pagination support
  go.mod
  go.sum
  go/plumbing/operations/list_account_audit_events_parameters.go
  go/plumbing/operations/list_form_submission_parameters.go
  go/plumbing/operations/list_form_submissions_parameters.go
  go/plumbing/operations/list_site_builds_parameters.go
  go/plumbing/operations/list_site_deploys_parameters.go
  go/plumbing/operations/list_site_submissions_parameters.go
  go/plumbing/operations/list_sites_for_account_parameters.go
  go/plumbing/operations/list_sites_parameters.go
  swagger.yml
Labels: type: feature

#281 Fix createSiteBuildHook and updateSiteBuildHook params
  swagger.yml
Labels: type: bug

#283 Remove broken screenshot
  README.md
Labels: type: bug

#284 Update go client
  go/models/build_hook_setup.go
  go/plumbing/operations/create_site_build_hook_parameters.go
  go/plumbing/operations/update_site_build_hook_parameters.go
Labels: type: chore

#275 Add getAccountBuildStatus
  go/models/build_status.go
  go/models/build_status_minutes.go
  go/plumbing/operations/get_account_build_status_parameters.go
  go/plumbing/operations/get_account_build_status_responses.go
  go/plumbing/operations/operations_client.go
  swagger.yml
Labels: type: feature

#286 Add prerender property to site
  go/models/site.go
  swagger.yml
Labels: type: chore

#288 chore: add release-please
  .github/workflows/release-please.yml
  .github/workflows/swagger-bump.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: proj/align-npm-publishing, type: chore

#290 fix(package.json): remove scripts no longer required and don't npm ci on swagger bump
  .github/workflows/swagger-bump.yml
  package.json
Labels: proj/align-npm-publishing, type: chore

#291 chore(actions): add labeler
  .github/workflows/labeler.yml
Labels: type: chore

#293 chore(prettier): disable CHANGELOG linting
  package.json
Labels: type: chore

#292 chore(actions): check uncomitted go source code changes
  .github/workflows/verify-go-src.yml
  .gitignore
Labels: type: chore

#294 chore(actions): use go v1.15.x
  .github/workflows/test.yml
  .github/workflows/verify-go-src.yml
Labels: type: chore

#297 Ignore cache directories in root of build directory when deploying
  go/porcelain/deploy.go
  go/porcelain/deploy_test.go
Labels: type: bug
