Repository netlify/open-api, pull requests merged in 2021-04, with the labels that each got.

#325 chore(release-please): use GitHub app token
  .github/workflows/release-please.yml
Labels: type: chore

#326 chore: automate npm publishing
  .github/workflows/release-please.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  package.json
Labels: type: chore

#331 feat: add internal endpoint updatePlugin
  go/models/plugin.go
  go/models/plugin_params.go
  go/plumbing/operations/operations_client.go
  go/plumbing/operations/update_plugin_parameters.go
  go/plumbing/operations/update_plugin_responses.go
  swagger.yml
Labels: type: feature

#333 fix: npm automation
  package.json
Labels: type: bug
