Repository netlify/open-api, pull requests merged in 2023-03, with the labels that each got.

#432 fix: add legal compliance footer
  package-lock.json
  src/docs/assets.js
  src/docs/footer.html
  src/docs/head.html
  src/docs/inject.js
  src/docs/styles.css
Labels: type: bug

#436 chore: update logo in docs
  api.png
  src/docs/netlify-logo.png
Labels: type: chore

#425 fix: upload a single file per sha
  go/porcelain/deploy.go
  go/porcelain/deploy_test.go
Labels: type: chore, type: bug
